"""initial schema

Revision ID: 35618af555c5
Revises: 
Create Date: 2026-04-20 15:04:42.387170

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '35618af555c5'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('comorbidities',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('foods',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('calories', sa.Numeric(precision=6, scale=2), nullable=False),
    sa.Column('proteins', sa.Numeric(precision=6, scale=2), nullable=False),
    sa.Column('fat', sa.Numeric(precision=6, scale=2), nullable=False),
    sa.Column('carbs', sa.Numeric(precision=6, scale=2), nullable=False),
    sa.Column('calcium', sa.Numeric(precision=6, scale=2), nullable=False),
    sa.Column('iron', sa.Numeric(precision=6, scale=2), nullable=False),
    sa.Column('vitamin_c', sa.Numeric(precision=6, scale=2), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('patients',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('lastname', sa.String(length=100), nullable=False),
    sa.Column('firstname', sa.String(length=100), nullable=False),
    sa.Column('gender', sa.Enum('FEMALE', 'MALE', name='genderenum'), nullable=False),
    sa.Column('birthdate', sa.Date(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('recipes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('appointments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('patient_id', sa.Integer(), nullable=False),
    sa.Column('date_time', sa.DateTime(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('type', sa.Enum('FIRST', 'FOLLOW_UP', 'CLOSURE', name='appointmentenum'), nullable=False),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('meal_plan',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('patient_id', sa.Integer(), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=False),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('patient_comorbidity',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('patient_id', sa.Integer(), nullable=False),
    sa.Column('comorbidity_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['comorbidity_id'], ['comorbidities.id'], ),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('patient_id', 'comorbidity_id', name='uc_patient_comorbidity')
    )
    op.create_table('patient_measurement',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('patient_id', sa.Integer(), nullable=False),
    sa.Column('height', sa.Numeric(precision=6, scale=2), nullable=False),
    sa.Column('weight', sa.Numeric(precision=6, scale=2), nullable=False),
    sa.Column('record_date', sa.Date(), server_default=sa.text('(CURRENT_DATE)'), nullable=False),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('recipe_food',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('recipe_id', sa.Integer(), nullable=False),
    sa.Column('food_id', sa.Integer(), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('unit', sa.Enum('GRAM', 'MGRAM', 'ML', 'CL', 'TSP', 'TBSP', 'UNIT', name='unitenum'), nullable=False),
    sa.ForeignKeyConstraint(['food_id'], ['foods.id'], ),
    sa.ForeignKeyConstraint(['recipe_id'], ['recipes.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('recipe_id', 'food_id', name='uc_recipe_food')
    )
    op.create_table('meal_plan_food',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('plan_id', sa.Integer(), nullable=False),
    sa.Column('food_id', sa.Integer(), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('period', sa.Enum('BREAKFAST', 'MORNING_SNACK', 'LUNCH', 'AFTERNOON_SNACK', 'DINNER', 'EVENING_SNACK', name='mealplanenum'), nullable=False),
    sa.Column('frequency', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['food_id'], ['foods.id'], ),
    sa.ForeignKeyConstraint(['plan_id'], ['meal_plan.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('plan_id', 'food_id', 'period', name='uc_meal_plan_food')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('meal_plan_food')
    op.drop_table('recipe_food')
    op.drop_table('patient_measurement')
    op.drop_table('patient_comorbidity')
    op.drop_table('meal_plan')
    op.drop_table('appointments')
    op.drop_table('recipes')
    op.drop_table('patients')
    op.drop_table('foods')
    op.drop_table('comorbidities')
    # ### end Alembic commands ###
